#pragma once

#include <algorithm>
#include <array>
#include <cstddef>
#include <string>

#include "EnemyType.hpp"
#include "EliteModifier.hpp"
#include "LootBias.hpp"

struct EnemyPackDefinition {
    std::string id;
    std::string name;
    std::string description;
    std::array<EnemyType, 6> enemies{};
    int enemyCount = 0;
    LootBias lootBias;
    int clearRewardDrops = 1;
    int leaderIndex = -1;
    std::string leaderName;
    std::string leaderDescription;
    std::array<EliteModifier, 2> leaderModifiers{
        EliteModifier::None, EliteModifier::None
    };
    float leaderDropMultiplier = 1.0f;
    int leaderBonusDrops = 0;
    int leaderExperienceMultiplier = 1;
    LootBias leaderLootBias;
    std::string leaderRewardDescription;
};

class EnemyPackLibrary {
public:
    static constexpr int ThemeCount = 8;
    static constexpr int PacksPerTheme = 3;

    static const std::array<EnemyPackDefinition, ThemeCount * PacksPerTheme>& all() {
        static const std::array<EnemyPackDefinition, ThemeCount * PacksPerTheme> packs = {{
            {
                "ashen-line-breaker",
                "Line Breakers",
                "Feral front line with a Ravager push",
                {EnemyType::Normal, EnemyType::Normal, EnemyType::Normal,
                 EnemyType::Charger, EnemyType::Elite, EnemyType::Normal},
                6,
                {AffixTag::Damage, 1.35f, AffixTag::Armor, 1.15f},
                1,
                4,
                "Cinderjaw",
                "A hardened empowered line captain that survives focused fire",
                {EliteModifier::Hardened, EliteModifier::Empowered},
                2.0f,
                2,
                2,
                {AffixTag::Damage, 1.70f, AffixTag::Armor, 1.25f},
                "Damage / Armor weighted | 2 guaranteed drops"
            },
            {
                "ashen-warden-court",
                "Ashen Warden Court",
                "A Warden anchors a slow, durable melee formation",
                {EnemyType::Warden, EnemyType::Normal, EnemyType::Normal,
                 EnemyType::Normal, EnemyType::Charger, EnemyType::Elite},
                6,
                {AffixTag::Survival, 1.35f, AffixTag::Armor, 1.20f},
                1,
                5,
                "Ashen Bulwark",
                "A rejuvenating hardened commander guarded by a Warden court",
                {EliteModifier::Hardened, EliteModifier::Rejuvenating},
                2.0f,
                2,
                2,
                {AffixTag::Survival, 1.70f, AffixTag::Armor, 1.25f},
                "Survival / Armor weighted | 2 guaranteed drops"
            },
            {
                "ashen-last-stand",
                "Last Stand",
                "Elite pressure backed by a compact melee screen",
                {EnemyType::Elite, EnemyType::Normal, EnemyType::Normal,
                 EnemyType::Charger, EnemyType::Warden, EnemyType::Normal},
                6,
                {AffixTag::Damage, 1.40f, AffixTag::Area, 1.15f},
                1,
                0,
                "Last Ember",
                "A stormbound captain that accelerates when the formation breaks",
                {EliteModifier::Swift, EliteModifier::Stormbound},
                2.0f,
                1,
                2,
                {AffixTag::Fire, 1.70f, AffixTag::Area, 1.25f},
                "Fire / Area weighted | 1 guaranteed drop"
            },
            {
                "storm-spitter-screen",
                "Spitter Screen",
                "Ranged pressure forces movement through the open field",
                {EnemyType::Ranged, EnemyType::Ranged, EnemyType::Elite,
                 EnemyType::Ranged, EnemyType::Charger, EnemyType::Summoner},
                6,
                {AffixTag::Projectile, 1.40f, AffixTag::AttackSpeed, 1.15f},
                1,
                2,
                "Storm Herald",
                "A stormbound empowered artillery leader with a long-range screen",
                {EliteModifier::Stormbound, EliteModifier::Empowered},
                2.0f,
                2,
                2,
                {AffixTag::Lightning, 1.75f, AffixTag::Projectile, 1.30f},
                "Lightning / Projectile weighted | 2 guaranteed drops"
            },
            {
                "storm-anchor-patrol",
                "Anchor Patrol",
                "A Hexbinder creates a protected ranged position",
                {EnemyType::Summoner, EnemyType::Ranged, EnemyType::Ranged,
                 EnemyType::Elite, EnemyType::Charger, EnemyType::Normal},
                6,
                {AffixTag::Lightning, 1.35f, AffixTag::Projectile, 1.20f},
                1,
                3,
                "Anchor of Glass",
                "A hardened stormbound anchor that protects a crossfire nest",
                {EliteModifier::Hardened, EliteModifier::Stormbound},
                2.0f,
                1,
                2,
                {AffixTag::Lightning, 1.70f, AffixTag::Armor, 1.25f},
                "Lightning / Armor weighted | 1 guaranteed drop"
            },
            {
                "storm-crossfire",
                "Crossfire Wing",
                "Chargers collapse on a ranged crossfire",
                {EnemyType::Ranged, EnemyType::Charger, EnemyType::Ranged,
                 EnemyType::Normal, EnemyType::Elite, EnemyType::Ranged},
                6,
                {AffixTag::AttackSpeed, 1.35f, AffixTag::Projectile, 1.20f},
                1,
                4,
                "Crossfire Prime",
                "A swift stormbound captain that collapses the ranged wing",
                {EliteModifier::Swift, EliteModifier::Stormbound},
                2.0f,
                2,
                2,
                {AffixTag::Projectile, 1.70f, AffixTag::AttackSpeed, 1.25f},
                "Projectile / Attack Speed weighted | 2 guaranteed drops"
            },
            {
                "venom-overgrowth",
                "Overgrowth",
                "Mixed elemental threats with a durable Warden",
                {EnemyType::Warden, EnemyType::Elite, EnemyType::Charger,
                 EnemyType::Normal, EnemyType::Summoner, EnemyType::Normal},
                6,
                {AffixTag::Poison, 1.40f, AffixTag::Area, 1.15f},
                1,
                1,
                "Rotbloom Keeper",
                "A hardened rejuvenating guardian rooted in toxic growth",
                {EliteModifier::Hardened, EliteModifier::Rejuvenating},
                2.0f,
                2,
                2,
                {AffixTag::Poison, 1.75f, AffixTag::Area, 1.25f},
                "Poison / Area weighted | 2 guaranteed drops"
            },
            {
                "venom-hunter-nest",
                "Hunter Nest",
                "A Summoner and Chargers punish stationary builds",
                {EnemyType::Summoner, EnemyType::Charger, EnemyType::Charger,
                 EnemyType::Normal, EnemyType::Elite, EnemyType::Normal},
                6,
                {AffixTag::Poison, 1.35f, AffixTag::Damage, 1.20f},
                1,
                4,
                "Venom Fang",
                "A swift empowered hunter that drives the pack forward",
                {EliteModifier::Swift, EliteModifier::Empowered},
                2.0f,
                1,
                2,
                {AffixTag::Poison, 1.70f, AffixTag::Damage, 1.25f},
                "Poison / Damage weighted | 1 guaranteed drop"
            },
            {
                "venom-bloom-guard",
                "Bloom Guard",
                "Elite and Warden defenses protect a poison-leaning screen",
                {EnemyType::Elite, EnemyType::Warden, EnemyType::Normal,
                 EnemyType::Normal, EnemyType::Charger, EnemyType::Summoner},
                6,
                {AffixTag::Poison, 1.45f, AffixTag::Survival, 1.15f},
                1,
                0,
                "Bloom Matriarch",
                "A rejuvenating volatile leader that protects the final growth",
                {EliteModifier::Rejuvenating, EliteModifier::Volatile},
                2.0f,
                2,
                2,
                {AffixTag::Poison, 1.80f, AffixTag::Survival, 1.30f},
                "Poison / Survival weighted | 2 guaranteed drops"
            },
            {
                "frost-shard-wall",
                "Shard Wall",
                "Wardens hold a cold-forged line while chargers break your escape route",
                {EnemyType::Warden, EnemyType::Charger, EnemyType::Normal,
                 EnemyType::Elite, EnemyType::Charger, EnemyType::Normal},
                6,
                {AffixTag::Cold, 1.45f, AffixTag::Area, 1.20f},
                1,
                3,
                "Rime Bastion",
                "A hardened rejuvenating captain that refuses to yield ground",
                {EliteModifier::Hardened, EliteModifier::Rejuvenating},
                2.0f,
                2,
                2,
                {AffixTag::Cold, 1.75f, AffixTag::Area, 1.30f},
                "Cold / Area weighted | 2 guaranteed drops"
            },
            {
                "frost-whiteout-crossfire",
                "Whiteout Crossfire",
                "Ranged wardens and chargers create a freezing crossfire",
                {EnemyType::Ranged, EnemyType::Warden, EnemyType::Charger,
                 EnemyType::Elite, EnemyType::Ranged, EnemyType::Normal},
                6,
                {AffixTag::Cold, 1.35f, AffixTag::Projectile, 1.20f},
                1,
                3,
                "Whiteout Marshal",
                "An empowered stormbound commander concealed by the blizzard",
                {EliteModifier::Stormbound, EliteModifier::Empowered},
                2.0f,
                2,
                2,
                {AffixTag::Cold, 1.70f, AffixTag::Projectile, 1.30f},
                "Cold / Projectile weighted | 2 guaranteed drops"
            },
            {
                "frost-frozen-procession",
                "Frozen Procession",
                "A Warden procession advances behind a volatile icebreaker",
                {EnemyType::Warden, EnemyType::Summoner, EnemyType::Charger,
                 EnemyType::Elite, EnemyType::Normal, EnemyType::Charger},
                6,
                {AffixTag::Cold, 1.40f, AffixTag::Survival, 1.15f},
                1,
                3,
                "Rime Processioner",
                "A rejuvenating volatile leader that turns every opening into a hazard",
                {EliteModifier::Rejuvenating, EliteModifier::Volatile},
                2.0f,
                2,
                2,
                {AffixTag::Cold, 1.75f, AffixTag::Survival, 1.25f},
                "Cold / Survival weighted | 2 guaranteed drops"
            },
            {
                "drowned-quill-line",
                "Quill Line",
                "Ranged archivists shelter behind a cold Warden screen",
                {EnemyType::Ranged, EnemyType::Warden, EnemyType::Normal,
                 EnemyType::Ranged, EnemyType::Elite, EnemyType::Normal},
                6,
                {AffixTag::Cold, 1.45f, AffixTag::Projectile, 1.20f},
                1,
                4,
                "Inkbound Archivist",
                "A hardened archivist that turns the formation into a freezing crossfire",
                {EliteModifier::Hardened, EliteModifier::Empowered},
                2.0f,
                2,
                2,
                {AffixTag::Cold, 1.75f, AffixTag::Projectile, 1.30f},
                "Cold / Projectile weighted | 2 guaranteed drops"
            },
            {
                "drowned-silt-court",
                "Siltbound Court",
                "Wardens and a Hexbinder hold a slow flooded corridor",
                {EnemyType::Warden, EnemyType::Summoner, EnemyType::Normal,
                 EnemyType::Elite, EnemyType::Charger, EnemyType::Normal},
                6,
                {AffixTag::Cold, 1.40f, AffixTag::Survival, 1.20f},
                1,
                3,
                "Siltbound Custodian",
                "A rejuvenating court captain keeps the drowned formation alive",
                {EliteModifier::Rejuvenating, EliteModifier::Hardened},
                2.0f,
                2,
                2,
                {AffixTag::Survival, 1.75f, AffixTag::Cold, 1.30f},
                "Survival / Cold weighted | 2 guaranteed drops"
            },
            {
                "drowned-undertow-crossfire",
                "Undertow Crossfire",
                "Chargers force movement through overlapping cold projectiles",
                {EnemyType::Ranged, EnemyType::Charger, EnemyType::Elite,
                 EnemyType::Normal, EnemyType::Warden, EnemyType::Ranged},
                6,
                {AffixTag::Area, 1.35f, AffixTag::Cold, 1.20f},
                1,
                2,
                "Undertow Marshal",
                "A volatile marshal collapses the crossfire when its formation breaks",
                {EliteModifier::Volatile, EliteModifier::Swift},
                2.0f,
                1,
                2,
                {AffixTag::Area, 1.70f, AffixTag::Cold, 1.30f},
                "Area / Cold weighted | 1 guaranteed drop"
            },
            {
                "obsidian-glassbreakers",
                "Glassbreakers",
                "Chargers and empowered elites rush through burning shard fields",
                {EnemyType::Elite, EnemyType::Charger, EnemyType::Normal,
                 EnemyType::Charger, EnemyType::Normal, EnemyType::Elite},
                6,
                {AffixTag::Fire, 1.45f, AffixTag::Damage, 1.20f},
                1,
                0,
                "Glassbreaker Prime",
                "An empowered forge captain drives both elite points into the player",
                {EliteModifier::Empowered, EliteModifier::Volatile},
                2.0f,
                2,
                2,
                {AffixTag::Fire, 1.80f, AffixTag::Damage, 1.30f},
                "Fire / Damage weighted | 2 guaranteed drops"
            },
            {
                "obsidian-furnace-anchor",
                "Furnace Anchor",
                "A Summoner anchors a durable forge guard and charger screen",
                {EnemyType::Summoner, EnemyType::Elite, EnemyType::Charger,
                 EnemyType::Normal, EnemyType::Normal, EnemyType::Warden},
                6,
                {AffixTag::Fire, 1.40f, AffixTag::Armor, 1.20f},
                1,
                1,
                "Furnace Castellan",
                "A hardened anchor protects the reliquary with a burning formation",
                {EliteModifier::Hardened, EliteModifier::Stormbound},
                2.0f,
                2,
                2,
                {AffixTag::Armor, 1.75f, AffixTag::Fire, 1.30f},
                "Armor / Fire weighted | 2 guaranteed drops"
            },
            {
                "obsidian-blackglass-rush",
                "Blackglass Rush",
                "Swift chargers collapse a damage-heavy melee wedge",
                {EnemyType::Charger, EnemyType::Ranged, EnemyType::Elite,
                 EnemyType::Charger, EnemyType::Normal, EnemyType::Normal},
                6,
                {AffixTag::Damage, 1.45f, AffixTag::Area, 1.20f},
                1,
                2,
                "Blackglass Ravager",
                "A swift ravager turns every opening into a burning charge",
                {EliteModifier::Swift, EliteModifier::Empowered},
                2.0f,
                1,
                2,
                {AffixTag::Damage, 1.80f, AffixTag::Area, 1.30f},
                "Damage / Area weighted | 1 guaranteed drop"
            },
            {
                "aether-lens-guard",
                "Lens Guard",
                "A charged Warden formation screens a ranged lens battery",
                {EnemyType::Warden, EnemyType::Ranged, EnemyType::Normal,
                 EnemyType::Elite, EnemyType::Normal, EnemyType::Charger},
                6,
                {AffixTag::Survival, 1.40f, AffixTag::Lightning, 1.20f},
                1,
                3,
                "Lens Custodian",
                "A hardened stormbound custodian protects the observatory focus",
                {EliteModifier::Hardened, EliteModifier::Stormbound},
                2.0f,
                2,
                2,
                {AffixTag::Survival, 1.75f, AffixTag::Lightning, 1.30f},
                "Mana / Lightning weighted | 2 guaranteed drops"
            },
            {
                "aether-void-choir",
                "Void Choir",
                "Summoners and ranged casters overload the field with charged fire",
                {EnemyType::Summoner, EnemyType::Ranged, EnemyType::Ranged,
                 EnemyType::Elite, EnemyType::Normal, EnemyType::Warden},
                6,
                {AffixTag::Lightning, 1.45f, AffixTag::Projectile, 1.20f},
                1,
                3,
                "Void Cantor",
                "A volatile cantor turns every summoned pulse into a lightning threat",
                {EliteModifier::Volatile, EliteModifier::Stormbound},
                2.0f,
                1,
                2,
                {AffixTag::Lightning, 1.80f, AffixTag::Projectile, 1.30f},
                "Lightning / Projectile weighted rewards | 1 guaranteed drop"
            },
            {
                "aether-overcharge",
                "Overcharge Wing",
                "Swift chargers collapse on a damage-heavy lens battery",
                {EnemyType::Elite, EnemyType::Charger, EnemyType::Ranged,
                 EnemyType::Ranged, EnemyType::Normal, EnemyType::Summoner},
                6,
                {AffixTag::Damage, 1.45f, AffixTag::Lightning, 1.20f},
                1,
                0,
                "Overcharge Prime",
                "An empowered captain accelerates the final collapse of the lens array",
                {EliteModifier::Swift, EliteModifier::Empowered},
                2.0f,
                2,
                2,
                {AffixTag::Damage, 1.80f, AffixTag::Survival, 1.25f},
                "Damage / Mana weighted rewards | 2 guaranteed drops"
            },
            {
                "sable-bone-garden",
                "Bone Garden",
                "Wardens anchor a venomous formation around gravebloom leaders",
                {EnemyType::Warden, EnemyType::Normal, EnemyType::Normal,
                 EnemyType::Summoner, EnemyType::Elite, EnemyType::Normal},
                6,
                {AffixTag::Poison, 1.45f, AffixTag::Survival, 1.20f},
                1,
                4,
                "Marrow Gardener",
                "A hardened warden cultivates poisonous ground around the pack",
                {EliteModifier::Hardened, EliteModifier::Rejuvenating},
                2.0f,
                2,
                2,
                {AffixTag::Poison, 1.85f, AffixTag::Survival, 1.30f},
                "Poison / Survival weighted | 2 guaranteed drops"
            },
            {
                "sable-venom-choir",
                "Venom Choir",
                "Summoners and ranged scavengers spread poison through the ruins",
                {EnemyType::Summoner, EnemyType::Ranged, EnemyType::Charger,
                 EnemyType::Elite, EnemyType::Normal, EnemyType::Warden},
                6,
                {AffixTag::Poison, 1.50f, AffixTag::Projectile, 1.20f},
                1,
                3,
                "Rot Cantor",
                "A volatile cantor turns every summon into a poisonous detonation",
                {EliteModifier::Volatile, EliteModifier::Swift},
                2.0f,
                1,
                2,
                {AffixTag::Poison, 1.90f, AffixTag::Projectile, 1.25f},
                "Poison / Projectile weighted rewards | 1 guaranteed drop"
            },
            {
                "sable-gravebloom",
                "Gravebloom Procession",
                "Elites and Chargers push through a damage-heavy toxic procession",
                {EnemyType::Elite, EnemyType::Charger, EnemyType::Normal,
                 EnemyType::Ranged, EnemyType::Normal, EnemyType::Summoner},
                6,
                {AffixTag::Poison, 1.45f, AffixTag::Area, 1.20f},
                1,
                0,
                "Bloom Executor",
                "An empowered captain accelerates the final spread of gravebloom spores",
                {EliteModifier::Empowered, EliteModifier::Volatile},
                2.0f,
                2,
                2,
                {AffixTag::Poison, 1.80f, AffixTag::Area, 1.30f},
                "Poison / Area weighted rewards | 2 guaranteed drops"
            }
        }};
        return packs;
    }

    static const EnemyPackDefinition& forMap(int templateIndex, int mapLevel, int sequence) {
        const int normalizedTemplate = ((templateIndex % ThemeCount) + ThemeCount) % ThemeCount;
        const int normalizedSequence = std::max(0, sequence) + std::max(1, mapLevel) - 1;
        const int index = normalizedTemplate * PacksPerTheme
            + (normalizedSequence % PacksPerTheme);
        return all()[static_cast<std::size_t>(index)];
    }
};
